import "./globals.css";
import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import { ConfigProvider } from "antd";
import StyledComponentsRegistry from "@/lib/AntdRegistry";
import { config } from "@/lib/AntdesingConfig";

const ubuntu = Ubuntu({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <StyledComponentsRegistry>
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: "#010886",
                borderRadius: 5,
              },
              components: {
                Tabs: {
                  inkBarColor: "#f0f0f0",
                  itemActiveColor: "#E9EBFD",
                  itemSelectedColor: "#010886",
                  algorithm: true,
                },
              },
            }}
          >
            {children}
          </ConfigProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
